### PR TITLE
Update Config.java

### PR DESCRIPTION
**Pull request by mikesa83**
Add flag for enabling a stop gap to Destroy's insane damage- quickly looked over old code, and see nothing insane about it, so temporarily want to just drop the damage by using a conditional Case on the damage output if this variable is true.

### CODE REVIEW

**Comment by everial** [comment]
So admittedly I've been out of it for awhile, but mind filling me in? Last time we had discussions about Destroy people were complaining that it was _underpowered_ and not worth using.

**Comment by mikesa83** [comment]
With erase it can do over 1000 damage, on a mage with not much gear (low sp
from items). Some fatalists have claimed they're quitting. Some of those
people did go from full HP to 0 though, so I can understand why they are
upset.

I compared the spell stats and magic damage calc to the old wk code (where
destroy did roughly 600?) And didn't find any functional differences. It is
different though, log in and ask in global lol.

**Comment by everial** [comment]
Do you have access to the DB for whichever server generated these complaints? If so it would be good to check if the underlying damage has changed there. If it's specific to that server could we move this to another file? 

This may have changed with time but we were trying to keep mainline similar to live; that's why you see files like westknights.sql with server-specific customizations.

**Comment by mikesa83** [comment]
Is that not what you're seeing? I don't have direct access to the server
DB. That being said, it should be a mirror of the updates in the master
branch. Have you tested it?

This doesn't affect live mirroring.

**Comment by Soren8** [comment]
Destroy's damage was changed in the DB on zelgo.net as a customization. Master branch's damage is normal.

**Comment by mikesa83** [comment]
Yup, heard you on the other thread, there were 3 requests involving that,
been busy but I'll rescind the ones re that info, thanks.

-Mike

**Comment by mikesa83** [comment]
P.S. you were right Everial *tips hat*

**Pull request closed without merging**
