### PR TITLE
Make access levels scalable, command set access level, invis/kill tweak

### PR DESCRIPTION
**Pull request by smith-j-travis**
- Make the gm/monitor system actually scalable and get rid of the stupid
.isMonitor check.
-- Now anyone with a minimum access level gets the isGm perks like not
being detected by mobs, can't die, etc.
-- Also adds customizable chat prefixes for different access levels
- Add [*] to the end of a player's name if they are invisible and you
have the .findinvis command enabled
- Add auto run to commands so you don't have to run them on login.
Example: .invis, .invul, .appearoffline for anyone who has access to
those commands
- Modded .kill to only allow you to kill players with an access level
lower than your own
- Added .promote GM command to promote/demote players to different
levels

### CODE REVIEW

**Comment by everial** [comment]
`L1Status` could check instead of leaving 200 hardcoded.

In `Enchant.java` why keep the `player.isGm()` checks? Alternatively could have `isGm()` just check against `ALT.getMaxAccessLevel()`? Apologies if I'm missing something obvious here. =)

Generally speaking, what's the appeal of having `.promote`? I understand it's convenient for testing and setup, but if you have a rogue/hacked/drunk/for the lulz gm you're in even more trouble.

**Comment by smith-j-travis** [comment]
Not sure what you mean about L1Status. Could you elaborate? I don't see anything hard-coded in L1Status.

Leaving in the .isGm in enchant is just me being paranoid... really wanted to make sure I wasn't accidentally creating a hole that could allow someone to always succeed on enchants.

In my mind, a GM/admin should never have to go to the backend database unless they're trying to do mass updates or look at logs. To avoid abuse, you could always create a new Admin access level that would be the only one with .promote, however this command already seemed to exist in the .settings command, so I just pulled it out and made it more user friendly.

**Comment by everial** [comment]
re `L1Status`: got my reds and greens mixed up; don't mind me.

re `Enchant.java`: makes sense.

re hitting database: fair enough. I'm just paranoid after seeing one server struggle after a gm made changes that others (including the ultimate head/owner) didn't want.

**Comment by smith-j-travis** [comment]
Yeah that's why I haven't committed it yet. I've asked soren to take a look and if he gives the go ahead I plan to merge in.

If he says no, I will probably still merge in the invis tweak and the auto run commands bit.. just not the new access level stuff and .promote

**Comment by tricid** [comment]
I like the changes and have no complaints with any of it.  

I won't merge it in myself, I feel like I'm too uninvolved to make that choice on my own, but it has my approval

I also massively approve of adding in commands to do things we normally have to do from the db itself.

**Comment by everial** [comment]
> I also massively approve of adding in commands to do things we normally have to do from the db itself. 

There used (maybe this never hit mainline--I can't find it right now) to be a command that just took raw queries and executed them...

**Pull request merged**
