### PR TITLE
Tarak drop rates and 10% rings

### PR DESCRIPTION
**Pull request by antonio-marino**
Tarak drops have been updated with new drop rates( Fix for #347 ). Also boosted the drop rate for 10% rings a little bit.

### CODE REVIEW

**Comment by smith-j-travis** [comment]
Was it verified that the skills for tarak are working as expected? If not, this shouldn't be implemented until Zyl is able to update them.

**Comment by antonio-marino** [comment]
I've fought him on my server. He is pretty tough. He's summoning mobs, doing really insane magic damage and using poly, do you know if he did anything else on live?

**Comment by smith-j-travis** [comment]
I'm not sure.. I never played when Tarak was in game. Might be worth while to have some players chime in, or maybe get in touch with Zyl in IRC.

**Comment by antonio-marino** [comment]
Take a look at these videos:
https://www.youtube.com/watch?v=snm9NNMLnTE
https://www.youtube.com/watch?v=FEyl3aTQJGQ

**Pull request merged**
