### PR TITLE
Added gradle.

### PR DESCRIPTION
**Pull request by probepark**

### CODE REVIEW

**Comment by bm3719** [comment]
I'm indifferent about switching to gradle.  I agree it's better than ant, but for a build as simple as ours, it doesn't give us much and places more onus on the people grabbing the repo to install another external tool.  Overall, I'd vote pass on it, but I'm okay with it if others would prefer it.

Also, we already have a Freenode channel for the project, and don't use gitter.  It's already pretty low-throughput as is, so we probably shouldn't split the real-time project talk.

**Comment by mikesa83** [comment]
+1 on simplicity Bruce

**Comment by probepark** [comment]
@bm3719 
I see.

**Comment by tricid** [comment]
I agree with bm3719.  Gradle can be useful for some projects but its just extra complication for this one.

**Pull request closed without merging**
