### PR TITLE
Lava golems now drop Fiery Coals

### PR DESCRIPTION
**Pull request by antonio-marino**
Fix for #359.

### CODE REVIEW

**Comment by smith-j-travis** [comment]
Where'd ya get the drop rates from? I tried looking online but didn't couldn't quickly find a source.

**Comment by antonio-marino** [comment]
0.3 (after 3x) seemed ok to me...I could'nt find a reliable source for me either. The other monster that drops this is harder to kill but has a much higher drop rate (1.45%).

**Comment by smith-j-travis** [comment]
Yeah 0.1% and 0.7% seem OK to me. I can't imagine what damage having these in that those rates could do. 

I think you're good to merge, but it might be a good idea to see if any of the other devs have a reliable site for drops. The only reference I can find is a mention on the WK forums and someone said like 0.001% would be a decent drop rate. (http://www.westknights.com/forums/viewtopic.php?f=11&t=1600&start=10)

**Comment by everial** [comment]
> I think you're good to merge, but it might be a good idea to see if any of the other devs have a reliable site for drops. The only reference I can find is a mention on the WK forums and someone said like 0.001% would be a decent drop rate. (http://www.westknights.com/forums/viewtopic.php?f=11&t=1600&start=10)

Just for some context here, the WK folks were trying to make them fairly rare (to avoid massive farming and +lots Fortified T-Shirts and keep Lasta farming interesting) so if you're encouraging a more LoA feel you might want a slightly higher rate.

**Comment by smith-j-travis** [comment]
I think I remember Soren saying that he wanted the server to be close to Dep, but from what I remember, the drop rates were fairly similar between LoA and Dep.

I think fortified T-Shirt is the top grade armour for a knight, so maybe a bit lower of a drop rate like 0.05% or something might be good for lava golems?

**Comment by antonio-marino** [comment]
Well I think its so easy to make a Fortified Shirt now that only noobs will hunt lava golems for it. Higher levels will probably find a mage friend and aoe for 10 mins for a lot of fiery coals.

**Comment by smith-j-travis** [comment]
Good point. I think you're good to merge in then.

It has conflicts you'll need to resolve first, though. I've never done that before through git.

**Comment by antonio-marino** [comment]
Do you see any conflicts? Cause I don't...git is probably drunk!

**Comment by smith-j-travis** [comment]
Yeah I don't see any either. The only thing I can think of is that your fork has conflicts and git is trying to be proactive by stopping the merge.

**Pull request merged**
